version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - - run: pip install -i https://test.pypi.org/simple/ Twimer==0.0.1
      - run:
          command: pytest
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
