version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: |
            pip3 install -r requirements.txt
            pip install -i https://test.pypi.org/simple/ Twimer==0.0.1
            python -m pytest
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
